// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbSZaJLqZYdesYdCVYVs4jnMhmHwQvFWg',
    appId: '1:1000843953341:web:629b4d4405ea17520163d4',
    messagingSenderId: '1000843953341',
    projectId: 'news-app-46467',
    authDomain: 'news-app-46467.firebaseapp.com',
    storageBucket: 'news-app-46467.appspot.com',
    measurementId: 'G-SLWMGJKZ5B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD33AEkPHnlDO41aJXDCy64zrLRaPR3OfY',
    appId: '1:1000843953341:android:5844f6161456a5740163d4',
    messagingSenderId: '1000843953341',
    projectId: 'news-app-46467',
    storageBucket: 'news-app-46467.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwQhS4tzvlrVQnEkoZN4QmgfKZOA3FKb4',
    appId: '1:1000843953341:ios:f05aa59d7a2a44bf0163d4',
    messagingSenderId: '1000843953341',
    projectId: 'news-app-46467',
    storageBucket: 'news-app-46467.appspot.com',
    iosBundleId: 'com.example.newsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDwQhS4tzvlrVQnEkoZN4QmgfKZOA3FKb4',
    appId: '1:1000843953341:ios:edd7d27e1548ece20163d4',
    messagingSenderId: '1000843953341',
    projectId: 'news-app-46467',
    storageBucket: 'news-app-46467.appspot.com',
    iosBundleId: 'com.example.newsApp.RunnerTests',
  );
}
